apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ekart-deployment
spec:
  selector:
    matchLabels:
      app: ekart
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ekart
    spec:
      serviceAccountName: sushmitham
      imagePullSecrets:
        - name: ecr-keysekart
      containers:
        - name: javacont
          image: 605134468487.dkr.ecr.ap-south-1.amazonaws.com/demo-repo:javav3 # Image that will be used to containers in the cluster
          command: ["/bin/sh", "-c", "sleep 9999999"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service 
metadata:
  name: ekart-svc
spec:
  type: NodePort
  selector:
    app: ekart
  ports:
  - targetPort: 8070
    port: 8070
    nodePort: 32000

